# -*- coding: utf-8 -*-
__author__ = 'raek'

observer_list={ 1664: 'hilfje@obskorps/svv',
                    1665: 'Marius@obskorps',
                    772: 'Kari@ObsKorps',
                    773: 'Hans-Joergen@ObsKorps',
                    775: 'Kaj@obskorps',
                    1068: 'martin@svv',
                    1418: 'AnneMariaLeune@obskorps',
                    267: 'Loewe@ObsKorps',
                    12: 'micke@Obskorps',
                    269: 'Christer@obskorps',
                    270: 'Bjoernulf@ObsKorps',
                    271: 'Patrik@ObsKorps',
                    16: 'Marianne@obskorps',
                    280: 'LyngenDavid@ObsKorps',
                    26: 'tor.olav.nystog@obskorps',
                    19: 'HaavardT@met',
                    788: 'Ragne@ObsKorps',
                    21: 'Leif@ObsKorps',
                    24: 'Bjoern M',
                    25: 'Albert',
                    794: 'Jonas.hansen@live.no',
                    155: 'geir@fjellsentralen',
                    260: 'svein loftsgarden',
                    282: 'martin@obskorps',
                    52: 'Rune@obskorps',
                    544: 'brit-siv@obskorps',
                    35: 'Joergen@obskorps',
                    38: 'birgit@NVE.no',
                    40: 'Halvor@NVE',
                    1578: 'finseronny@obskorps',
                    44: 'Bent Vidar',
                    45: 'jostein@nve',
                    814: 'vd',
                    1076: 'JanR@ObsKorps',
                    55: 'torolav@fjellsentralen',
                    185: 'FrodeHansen@ObsKorps',
                    1338: 'Nils@obskorps',
                    1083: 'steinar@obskorps',
                    60: 'Aadne@ObsKorps',
                    1085: 'magnus@obskorps',
                    1598: 'Martine@SVV',
                    799: 'TC@ObsKorps',
                    580:'SindreH@ObsKorps',
                    839: 'Goeran@ObsKorps',
                    201: 'Urpu@Romsdal',
                    1610: 'Johannes@obskorps',
                    203: 'MagnusH@obskorps',
                    76: 'Pelle',
                    77: 'Odd-Arne@NVE',
                    594: 'Helen@ObsKorps',
                    1243: 'stiglo@obskorps',
                    94: 'OscarAlmgren',
                    227: 'solveig@NVE',
                    741: 'ToreV@met',
                    742: 'Ida@met',
                    746: 'Jimmy Halvardsson',
                    108: 'EspenN@NVE',
                    749: 'Espen@ObsKorps',
                    1646: 'Olav@svv',
                    111: 'JonasD@ObsKorps',
                    112: 'Steinar@ObsKorps',
                    1653: 'Rolf P@obskorps',
                    759: 'madspaatopp@senjaobs',
                    762: 'mortenh@obskorps',
                    1151: 'krikar',
                    239: 'rayvedal'}